services:
  terraform:
    image: hashicorp/terraform:light
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    entrypoint: ''
    command: sh
    volumes:
      - C:/0/desafio-devops/desafio-devops:/app
    